routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TeleConsultationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth',])->group(function () {

  Route::get('home', 'HomeController@index')->name('home');
  Route::resource('logins', 'LoginController');
  Route::resource('user',   'UserController');
  Route::resource('permission', 'PermissionController');
  Route::get('logs', 'HomeController@logs')->name('logs');
  Route::resource('roles',   'RolesController');
  Route::resource('services',   'ServicesController');
  Route::resource('customers',   'CustomersController');

  Route::resource('campus',   'CampusesController');
  Route::resource('invoice',   'InvoiceController');
  Route::get('invoice/customers/{idcustomer}', 'InvoiceController@getcustomer');
  Route::get('invoice/service/{idservice}', 'InvoiceController@getservice');
  Route::get('invoice/cities/{departament}', 'CustomersController@cities');
  Route::resource('pos',   'PosController');
  Route::get('pos/customers/{idcustomer}', 'InvoiceController@getcustomer');
  Route::get('pos/service/{idservice}', 'InvoiceController@getservice');
  Route::get('pos/cities/{departament}', 'CustomersController@cities');
  Route::resource('notacredit',   'CreditNoteController');
  Route::get('notacredit/invoice/{idinvoice}', 'CreditNoteController@getInvoiceById');
  Route::resource('availability',   'AvailabilityController');
  Route::resource('quote',   'QuoteController');
  Route::post('quote/pofesional', 'QuoteController@getquoteprofesional');
  Route::get('clinic-history/customer/{id}', 'ClinicHistoryController@byidcustomer');
  Route::resource('clinic-history',   'ClinicHistoryController');
  Route::resource('quoteanamnesis',   'QuoteAnamnesisController');
  Route::resource('extraoralexam',   'QuoteExtraOralExamController');
  Route::resource('dentalexam',   'QuoteDentalExamController');
  Route::resource('customerodontogram',   'QuoteCustomerOdontogramController');
  Route::get('getodontograma', 'QuoteCustomerOdontogramController@getOdontograma');
  Route::get('getHallazgosDientePaciente', 'QuoteCustomerOdontogramController@getHallazgosDientePaciente');
  Route::resource('typequote',   'TypeQuoteController');
  Route::resource('quotation',   'QuotationController');
  Route::get('quotation/customers/{idcustomer}', 'QuotationController@getcustomer');
  Route::get('quotation/service/{idservice}', 'QuotationController@getservice');
  Route::get('quotation/cities/{departament}', 'QuotationController@cities');
  Route::resource('reportinvoicepos',   'ReportInvoicePosController');
  Route::resource('reportinvoiceelectronic',   'ReportInvoiceElectronicController');
  Route::resource('reportinvoicequotation',   'ReportInvoiceQuotationController');
  Route::resource('tele-consultation',   'TeleConsultationController');
  Route::resource('tele-consultation',   'TeleConsultationController');
  Route::resource('checkoutpayment',   'PaymentController');
  Route::get('/tele-consultation/meet/{meet}', [TeleConsultationController::class, 'show'])->name('show');
});
Route::get('customers/cities/{departament}', 'CustomersController@cities');
Route::get('/', 'HomeaplicationController@index')->name('home');
Route::get('/registro', 'CustomersController@register')->name('registro');
Route::post('registercustomer', 'CustomersController@registercustomer')->name('registercustomer');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Traits\HasRoles;
use Vinkla\Hashids\Facades\Hashids;


class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    use HasRoles;

    protected $primaryKey = 'id';
    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name', 'lastname', 'email', 'password', 'status','username','genero','campuse_id'
    ];

    protected $hidden = [];

    protected $appends = ['full_name'];


    protected $searchable = [
        'columns' => [
          'users.name' => 5,
          'users.lastname' => 5,
        ]
    ];

    protected $guard_name = 'web';

    /*
    |
    | ** Relationships model **
    |
    */

    public function logins()
    {
        return $this->hasMany('App\Models\Login','user_id');
    }

    /*
    |
    | ** Accesors model **
    |
    */

     public function getDisplayNameAttribute()
     {
         return trim(str_replace( '  ', ' ',  "{$this->name} {$this->lastname}")) ;
     }


    public function getDisplayStatusAttribute()
    {
        return $this->status == 1 ? 'Activo' : 'Denegado';
    }

    /*
    |
    | ** Mutators model **
    |
    */

    public function setPasswordAttribute($attribute)
    {
        if (! empty($attribute))
        {
           $this->attributes['password'] = strlen($attribute) < 60 ? bcrypt($attribute) : $attribute;
        }
    }

    /*
    |
    | ** Send the custom password reset notification **
    |
    */

    public function getEncodeIDAttribute()
    {
        return Hashids::encode($this->id);
    }
    public function campus()
    {
        return $this->belongsTo(Campuses::class, 'campuse_id');
    }


}

resources/views/admin/clinichistory_show/partials/cursores.blade.php
<div class="cursor cursor-1" id="diente-18" data-diente="18" data-orden="1"></div>
<div class="cursor cursor-2" id="diente-17" data-diente="17" data-orden="2"></div>
<div class="cursor cursor-3" id="diente-16" data-diente="16" data-orden="3"></div>
<div class="cursor cursor-4" id="diente-15" data-diente="15" data-orden="4"></div>
<div class="cursor cursor-5" id="diente-14" data-diente="14" data-orden="5"></div>
<div class="cursor cursor-6" id="diente-13" data-diente="13" data-orden="6"></div>
<div class="cursor cursor-7" id="diente-12" data-diente="12" data-orden="7"></div>
<div class="cursor cursor-8" id="diente-11" data-diente="11" data-orden="8"></div>
<div class="cursor cursor-9" id="diente-21" data-diente="21" data-orden="9"></div>
<div class="cursor cursor-10" id="diente-22" data-diente="22" data-orden="10"></div>
<div class="cursor cursor-11" id="diente-23" data-diente="23" data-orden="11"></div>
<div class="cursor cursor-12" id="diente-24" data-diente="24" data-orden="12"></div>
<div class="cursor cursor-13" id="diente-25" data-diente="25" data-orden="13"></div>
<div class="cursor cursor-14" id="diente-26" data-diente="26" data-orden="14"></div>
<div class="cursor cursor-15" id="diente-27" data-diente="27" data-orden="15"></div>
<div class="cursor cursor-16" id="diente-28" data-diente="28" data-orden="16"></div>
<div class="cursor cursor-17" id="diente-55" data-diente="55" data-orden="17"></div>
<div class="cursor cursor-18" id="diente-54" data-diente="54" data-orden="18"></div>
<div class="cursor cursor-19" id="diente-53" data-diente="53" data-orden="19"></div>
<div class="cursor cursor-20" id="diente-52" data-diente="52" data-orden="20"></div>
<div class="cursor cursor-21" id="diente-51" data-diente="51" data-orden="21"></div>
<div class="cursor cursor-22" id="diente-61" data-diente="61" data-orden="22"></div>
<div class="cursor cursor-23" id="diente-62" data-diente="62" data-orden="23"></div>
<div class="cursor cursor-24" id="diente-63" data-diente="63" data-orden="24"></div>
<div class="cursor cursor-25" id="diente-64" data-diente="64" data-orden="25"></div>
<div class="cursor cursor-26" id="diente-65" data-diente="65" data-orden="26"></div>
<div class="cursor cursor-27" id="diente-85" data-diente="85" data-orden="27"></div>
<div class="cursor cursor-28" id="diente-84" data-diente="84" data-orden="28"></div>
<div class="cursor cursor-29" id="diente-83" data-diente="83" data-orden="29"></div>
<div class="cursor cursor-30" id="diente-82" data-diente="82" data-orden="30"></div>
<div class="cursor cursor-31" id="diente-81" data-diente="81" data-orden="31"></div>
<div class="cursor cursor-32" id="diente-71" data-diente="71" data-orden="32"></div>
<div class="cursor cursor-33" id="diente-72" data-diente="72" data-orden="33"></div>
<div class="cursor cursor-34" id="diente-73" data-diente="73" data-orden="34"></div>
<div class="cursor cursor-35" id="diente-74" data-diente="74" data-orden="35"></div>
<div class="cursor cursor-36" id="diente-75" data-diente="75" data-orden="36"></div>
<div class="cursor cursor-37" id="diente-48" data-diente="48" data-orden="37"></div>
<div class="cursor cursor-38" id="diente-47" data-diente="47" data-orden="38"></div>
<div class="cursor cursor-39" id="diente-46" data-diente="46" data-orden="39"></div>
<div class="cursor cursor-40" id="diente-45" data-diente="45" data-orden="40"></div>
<div class="cursor cursor-41" id="diente-44" data-diente="44" data-orden="41"></div>
<div class="cursor cursor-42" id="diente-43" data-diente="43" data-orden="42"></div>
<div class="cursor cursor-43" id="diente-42" data-diente="42" data-orden="43"></div>
<div class="cursor cursor-44" id="diente-41" data-diente="41" data-orden="44"></div>
<div class="cursor cursor-45" id="diente-31" data-diente="31" data-orden="45"></div>
<div class="cursor cursor-46" id="diente-32" data-diente="32" data-orden="46"></div>
<div class="cursor cursor-47" id="diente-33" data-diente="33" data-orden="47"></div>
<div class="cursor cursor-48" id="diente-34" data-diente="34" data-orden="48"></div>
<div class="cursor cursor-49" id="diente-35" data-diente="35" data-orden="49"></div>
<div class="cursor cursor-50" id="diente-36" data-diente="36" data-orden="50"></div>
<div class="cursor cursor-51" id="diente-37" data-diente="37" data-orden="51"></div>
<div class="cursor cursor-52" id="diente-38" data-diente="38" data-orden="52"></div>

<div class="recuadro recuadro-1"></div>
<div class="recuadro recuadro-2"></div>
<div class="recuadro recuadro-3"></div>
<div class="recuadro recuadro-4"></div>
<div class="recuadro recuadro-5"></div>
<div class="recuadro recuadro-6"></div>
<div class="recuadro recuadro-7"></div>
<div class="recuadro recuadro-8"></div>
<div class="recuadro recuadro-9"></div>
<div class="recuadro recuadro-10"></div>
<div class="recuadro recuadro-11"></div>
<div class="recuadro recuadro-12"></div>
<div class="recuadro recuadro-13"></div>
<div class="recuadro recuadro-14"></div>
<div class="recuadro recuadro-15"></div>
<div class="recuadro recuadro-16"></div>
<div class="recuadro recuadro-17"></div>
<div class="recuadro recuadro-18"></div>
<div class="recuadro recuadro-19"></div>
<div class="recuadro recuadro-20"></div>
<div class="recuadro recuadro-21"></div>
<div class="recuadro recuadro-22"></div>
<div class="recuadro recuadro-23"></div>
<div class="recuadro recuadro-24"></div>
<div class="recuadro recuadro-25"></div>
<div class="recuadro recuadro-26"></div>
<div class="recuadro recuadro-27"></div>
<div class="recuadro recuadro-28"></div>
<div class="recuadro recuadro-29"></div>
<div class="recuadro recuadro-30"></div>
<div class="recuadro recuadro-31"></div>
<div class="recuadro recuadro-32"></div>
<div class="recuadro recuadro-33"></div>
<div class="recuadro recuadro-34"></div>
<div class="recuadro recuadro-35"></div>
<div class="recuadro recuadro-36"></div>
<div class="recuadro recuadro-37"></div>
<div class="recuadro recuadro-38"></div>
<div class="recuadro recuadro-39"></div>
<div class="recuadro recuadro-40"></div>
<div class="recuadro recuadro-41"></div>
<div class="recuadro recuadro-42"></div>
<div class="recuadro recuadro-43"></div>
<div class="recuadro recuadro-44"></div>
<div class="recuadro recuadro-45"></div>
<div class="recuadro recuadro-46"></div>
<div class="recuadro recuadro-47"></div>
<div class="recuadro recuadro-48"></div>
<div class="recuadro recuadro-49"></div>
<div class="recuadro recuadro-50"></div>
<div class="recuadro recuadro-51"></div>
<div class="recuadro recuadro-52"></div>

resources/views/admin/clinichistory_show/partials/form.blade.php
<form class="form" role="form" id="main-form" autocomplete="off">
                            <input type="hidden" id="_url" value="{{ url('customers',[$customer->encode_id]) }}">
                            <input type="hidden" id="_token" value="{{ csrf_token() }}">
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="first_name">Nombre</label>
                                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Nombre" value="{{ $customer->first_name }}">
                                        <span class="missing_alert text-danger" id="first_name_alert"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="last_name">Apellido</label>
                                        <input type="text" id="last_name" name="last_name" class="form-control" placeholder="Apellido" value="{{ $customer->last_name }}">
                                        <span class="missing_alert text-danger" id="last_name_alert"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="type">Tipo </label>
                                        <select  id="type" name="type" class="form-control">
                                            <option value="PERSONA_JURIDICA" {{ ($customer->type=='PERSONA_JURIDICA')? "selected" : "" }}>Persona Juridica</option>
                                            <option value="PERSONA_NATURAL" {{ ($customer->type=='PERSONA_NATURAL')? "selected" : "" }}>Persona Natural</option>
                                        </select>
                                        <span class="missing_alert text-danger" id="type_alert"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="identification_type">Tipo de documento</label>
                                        <select  id="identification_type" name="identification_type" class="form-control">
                                            <option value="CC" {{ ($customer->identification_type=='CC')? "selected" : "" }}>Cédula</option>
                                            <option value="NIT" {{ ($customer->identification_type=='NIT')? "selected" : "" }}>Nit</option>
                                            <option value="PASAPORTE" {{ ($customer->identification_type=='PASAPORTE')? "selected" : "" }}>Pasaporte</option>
                                            <option value="RC" {{ ($customer->identification_type=='RC')? "selected" : "" }}>RC</option>
                                            <option value="TI" {{ ($customer->identification_type=='TI')? "selected" : "" }}>TI</option>
                                            <option value="TE" {{ ($customer->identification_type=='TE')? "selected" : "" }}>TE</option>
                                            <option value="CE" {{ ($customer->identification_type=='CE')? "selected" : "" }}>CE</option>
                                            <option value="IE" {{ ($customer->identification_type=='IE')? "selected" : "" }}>IE</option>
                                            <option value="NIT_OTRO_PAIS" {{ ($customer->identification_type=='NIT_OTRO_PAIS')? "selected" : "" }}>Nit otro país</option>
                                        </select>
                                        <span class="missing_alert text-danger" id="identification_type_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="identification">Identificación</label>
                                        <input type="number" id="identification" name="identification" class="form-control" placeholder="Identificación" value="{{ $customer->identification }}">
                                        <span class="missing_alert text-danger" id="identification_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="regimen">Regimen</label>
                                        <select  id="regimen" name="regimen" class="form-control">
                                            <option value="SIMPLE"  {{ ($customer->regimen=='SIMPLE')? "selected" : "" }}>Simple</option>
                                            <option value="ORDINARIO"  {{ ($customer->regimen=='ORDINARIO')? "selected" : "" }}>Ordinario</option>
                                            <option value="GRAN_CONTRIBUYENTE"  {{ ($customer->regimen=='GRAN_CONTRIBUYENTE')? "selected" : "" }}>Grean Contribuyente</option>
                                            <option value="AUTORRETENEDOR"  {{ ($customer->regimen=='AUTORRETENEDOR')? "selected" : "" }}>Autorretenedor</option>
                                            <option value="AGENTE_RETENCION_IVA"  {{ ($customer->regimen=='AGENTE_RETENCION_IVA')? "selected" : "" }}>Agente Retención IVA</option>
                                        </select>
                                        <span class="missing_alert text-danger" id="regimen_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="departament_id">Departamento</label>
                                        <select  id="departament_id" name="departament_id" class="form-control">
                                            <option value="">Seleccione</option>
                                            @foreach( $deptos as $key => $value )
                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                            @endforeach
                                        </select>
                                        <span class="missing_alert text-danger" id="departament_id_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="city_id">Ciudad</label>
                                        <select  id="city_id" name="city_id" class="form-control">
                                            <option value="">Seleccione</option>
                                        </select>
                                        <span class="missing_alert text-danger" id="city_id_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="phone">Teléfono</label>
                                        <input type="number" id="phone" name="phone" class="form-control" placeholder="Teléfono" value="{{ $customer->phone }}">
                                        <span class="missing_alert text-danger" id="phone_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="email">E-mail</label>
                                        <input type="email" id="email" name="email" class="form-control" placeholder="E-mail" value="{{ $customer->email }}">
                                        <span class="missing_alert text-danger" id="email_alert"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="address_line">Dirección</label>
                                        <input type="text" id="address_line" name="address_line" class="form-control" placeholder="Dirección" value="{{ $customer->address_line }}">
                                        <span class="missing_alert text-danger" id="address_line_alert"></span>
                                    </div>
                                </div>



                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="city-column">Estado</label>
                                        <div class="demo-inline-spacing">
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="state" id="inlineRadio1" value="1" {{ ($customer->state=="1")? "checked" : "" }}>
                                                <label class="form-check-label" for="inlineRadio1">Activo</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="state" id="inlineRadio2" {{ ($customer->state=="0")? "checked" : "" }}>
                                                <label class="form-check-label" for="inlineRadio2">Desactivo</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>






                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary me-1 waves-effect waves-float waves-light ajax" id="submit"><i id="ajax-icon" class="fa fa-save"></i> Guardar</button>
                                </div>
                            </div>
                        </form>

@push('scripts')

<script src="{{ asset('js/admin/customers/edithistory.js') }}"></script>
@endpush

resources/views/admin/clinichistory_show/partials/modallistadehallazgos.blade.php
<!-- Modal -->
<div class="modal fade" id="ModalOdontogramaDetalle" tabindex="-1" aria-labelledby="ModalOdontogramaDetalleLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalOdontogramaDetalleLabel">Lista de Hallazgos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                    <th>Nombre</th>
                    <th>Categoria</th>
                    <th>Diente</th>
                    <th>Diente Final</th>
                    <th>Estado</th>
                    <th>Dibujo</th>
                    <th>Especificaciones</th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

resources/views/admin/clinichistory_show/partials/odontograma.blade.php
<div class="panel-body">
  <div class="row">
    <div class="col-md-12">
        <div id="imprimir" style="width: 800px"></div>
    </div>
    <div class="col-md-8" id="OdontogramaImprimir">
      <div id="odontograma">
        <div id="odontograma-contenido" class="detalle" data-marcaClass="">
          <img src="{{ asset('images/plantilla_odontograma.png') }}" style="max-width: 100%;" />
          <div id="cursoresRecuadros">           
              @include('admin.clinichistory.partials.cursores')
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      @include('admin.clinichistory.partials.odontogramanav')
    </div>
  </div>
</div>


@include('admin.clinichistory.partials.modallistadehallazgos')

@include('admin.clinichistory.partials.modalagregarhallazgo')


<div id="ModalCapturarOdontograma" class="modal fade" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <form id="FormGuardarCapturaOdontograma" action="" method="POST">
        <input type="hidden" name="paciente">
        <input type="hidden" name="tipo">
        <input type="hidden" name="imgData">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Odontograma Capturado</h4>
        </div>
        <div class="modal-body">
          <div id="ImagenOdontogramaCapturado">
            
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger pull-left" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
          <button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Guardar</button>
        </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



@push('scripts')

{{-- Create the chart with javascript using canvas --}}
    <script>
        // Get Canvas element by its id
        employee_chart = document.getElementById('employee').getContext('2d');
        chart = new Chart(employee_chart,{
            type:'line',
            data:{
                labels:[
                    /*
                        this is blade templating.
                        we are getting the date by specifying the submonth
                     */
                    '{{Carbon\Carbon::now()->subMonths(3)->toFormattedDateString()}}',
                    '{{Carbon\Carbon::now()->subMonths(2)->toFormattedDateString()}}',
                    '{{Carbon\Carbon::now()->subMonths(1)->toFormattedDateString()}}',
                    '{{Carbon\Carbon::now()->subMonths(0)->toFormattedDateString()}}'
                    ],
                datasets:[{
                    label:'Usuarios guardados en los últimos 4 meses.',
                    data:[
                        
                        '{{$emp_count_4}}',
                        '{{$emp_count_3}}',
                        '{{$emp_count_2}}',
                        '{{$emp_count_1}}'
                    ],
                    backgroundColor: [
                        'rgba(178,235,242 ,1)'
                    ],
                    borderColor: [
                        'rgba(0,150,136 ,1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            }
        });
    </script>
@endpush